services:
  app:
    image: ${IMAGE}
    pull_policy: "missing"
    init: true
    volumes:
      - type: bind
        source: ${PWD}
        target: ${PWD}
        consistency: "consistent"
      # Add more volumes here - note that /home/appuser is the home dir
    entrypoint: /home/appuser/show-help-in-app-container-then-wait.sh
    working_dir: ${PWD}
    environment:
      TERM: ${TERM}
      PROJECT_ROOT: ${PWD}
    # Add ports here


